---
title: "Eda la1"
Author: Haripriya, H Sai Sravya
date: "2023-05-17"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r}
eda1 <- read.csv("C:/Users/sravy/Desktop/all_stocks_5yr.csv")
View(eda1)
data(eda1)

```

```{r}
str(eda1)

```

```{r}
summary(eda1)
```

```{r}
plot(eda1)
```

```{r}
mean(eda1$volume)
```

```{r}
table(eda1$volume)
```

```{r}
subset(eda1)
```

```{r}
```

```{r}
boxplot(eda1$volume)
```

```{r}
boxplot(eda1$high)
```

```{r}
table(eda1$high)
```

```{r}
scale(eda1$low)
```

```{r}
```

```{r}
boxplot(eda1$low)
```

```{r}
ls()
```

```{r}
ls(pattern = 'n')
```

```{r}
str(eda1$high)
```

```{r}
ls.str(pattern = 've')
unique(eda1$low)
```

```{r}
nrow(eda1)
```

```{r}
ncol(eda1)
```

```{r}
cat("\nColumn:",ncol(eda1$high))
```

```{r}
cumsum(eda1$high)
```

```{r}
cumprod(eda1$`close`)
```

```{r}
cummin(eda1$open)
```

```{r}
rev(eda1$close)
```

```{r}
boxplot(eda1$`open`)
```

```{r}
boxplot(eda1$`close`)
```

```{r}
```

```{r}

```

```{r}
help()
```

```{r}
duplicated(eda1)
```

```{r}
rev(eda1$close)
```

```{r}
cummax(eda1$open)
```

```{r}
cumprod(eda1$`high`)
```

```{r}
log2(eda1$open) 
```

```{r}
attributes(eda1)
```

```{r}
stem(eda1$low)
```

```{r}
log10(eda1$volume) 
```

```{r}
require(lattice)
bwplot(eda1$volume)
```

```{r}
hist(eda1$low
```

```{r}
power.t.test(n=20, delta=.1, sd=.4, sig.level=.05)
```

```{power.t.test(n=20, delta=.1, sd=.4, sig.level=.05)}

```

```{r}
power.t.test(n=20, delta=.1, sd=.4, sig.level=.05)

```

```{r}
power.t.test(delta=.1, sd=.4, sig.level=.05, power=.8)
```

```{r}
hist(eda1$volume)
```

```{r}
1 - ppois(7, 4.2)
```

```{r}
ppois(1, 4.8)

```

```{r}
dpois(2:7, 4.2)
```

```{r}
dbinom(0,5, .5)

```

```{r}
sum(dbinom(0:2, 5, .5))

```

```{r}
table(rbinom(10000, 5, .5)) / 10000
```

```{r}
binom.test(29, 200, .21)
```

```{r}
1 - pchisq(3.1309, 5)
```

```{r}
pchisq(3.1309, df=5, lower.tail=F)
```

```{r}
qchisq(c(.001,.005,.01,.025,.05,.95,.975,.99,.995,.999), 2) 
```

```{r}
prop.test(29, 200, .21)
```

```{r}
plot(eda1$high)
```

```{r}
plot(eda1$volume)
```

```{r}
sample(eda1$volume)
```

```{r}
hist(eda1$open)
```

```{r}
barplot(eda1$open)
```

```{r}
barplot(eda1$close)
```

```{r}
stem(eda1$volume)
```

```{r}
stem(eda1$open)
```

```{r}
hist(eda1$close)
```

```{r}
c(eda1)
```

```{r}
require(lattice)
```

```{r}
pretty(eda1$high)
```

```{r}
pretty(eda1$low)
```

```{r}
barplot(eda1$volume)
```

```{r}
lowess(eda1)
```

```{r}
is.data.frame(eda1)

```

```{r}
is.name(eda1)

```

```{r}
identity(eda1)
```

```{r}
formatC(eda1$volume)
```

```{r}
floor(eda1$open)
```

```{r}
tail(eda1)
```

```{r}
sign(eda1$volume)

```

```{r}
mad((eda1$close))
```

```{r}
pmax((eda1$open))
```

```{r}
log2(eda1$close)
```

```{r}
exp(eda1$high)
```

```{r}
cummin(eda1$low)
```

```{r}
class(eda1)
```

```{r}
exp(eda1$low)
```

```{r}
rep(eda1)
```

```{r}
seq(eda1)
```

```{r}
dim(eda1)
```

```{r}
var(eda1$high)
```

```{r}
sum(eda1$volume)
```

```{r}
sd(eda1$volume)
```

```{r}
median(eda1$volume)
```

```{r}
names(eda1)
```

```{r}
length(eda1)
```

```{r}
cumprod(eda1$high)
```

```{r}
nrow(eda1)
```

```{r}
cumsum(eda1$close)
```

```{r}
scale(eda1$high)
```

```{r}
sort(eda1$low)
```

```{r}
res<- quantile(eda1$volume, c(0.5,0.7,0.9),na.rm = TRUE)
res
```
